#'default' profile only 
  

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    restart:
      enabled: true      
    refresh:
      enabled: true    
        
server:
  port: 8080
spring:
  application:
    name: spring-micro-elastic
  cloud:
    kubernetes:
      discovery:
        all-namespaces: true
        enabled: true 
      config:
        enabled: true
        name: ${spring.application.name}
        namespace: default
      reload:
        enabled: true
        monitoring-config-maps: true
        monitoring-secrets: true
        strategy: refresh
        mode: event
        period: 15s
               
  profiles:
    active: dev
  sleuth:
    sampler:
      probability: 1.0
    traceId128: true
    enabled: true
  zipkin:
    enabled: true
    
spring-micro-elastic:
  maximum: 8888
  minimum: 88
last:
  applied:
    profile: application_default
ribbon:
    http:
      client:
         enabled: true     
  
    
#'dev' profile only 
--- 
spring:
  profiles: dev 
#over riding the value 
spring-micro-elastic:
#  maximum: 5555
  minimum: 22
last:
  applied:
    profile: application_dev 
 
#'prod' profile only 
--- 
spring:
  profiles: prod 
  
spring-micro-elastic:
  maximum: 9999
  minimum: 99
last:
  applied:
    profile: application_prod 
    