#'default' profile only 
management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 8080
spring:
  application:
    name: spring-micro-elastic
  cloud:
    kubernetes:
      discovery:
        all-namespaces: true
        enabled: false    
  profiles:
    active: dev
  sleuth:
    sampler:
      probability: 1.0
    traceId128: true
    enabled: true
  zipkin:
    enabled: true
    
spring-micro-elastic:
  maximum: 8888
  minimum: 88
    
#'dev' profile only 
--- 
spring:
  profiles: dev 
#over riding the value 
spring-micro-elastic:
#  maximum: 5555
  minimum: 22
 
#'prod' profile only 
--- 
spring:
  profiles: prod 
  
spring-micro-elastic:
  maximum: 9999
  minimum: 99
    