kind: ConfigMap
apiVersion: v1
metadata:
  name: spring-micro-site-crawler
data:
  application.yml: |-
      #'default' profile only
      #'dev' profile only 
      --- 
      spring:
        profiles: dev 
      
      #'prod' profile only 
      --- 
      spring:
        profiles: prod 