kind: ConfigMap
apiVersion: v1
metadata:
  name: spring-micro-site-crawler
data:
  application.yml: |-
        #'default' profile only
        management:
          endpoints:
            web:
              exposure:
                include: '*'
          endpoint:
              restart:
                enabled: true      
              refresh:
                enabled: true    
                         
        server:
          port: 8100
        spring:
          application:
            name: spring-micro-site-crawler
          cloud:
            kubernetes:
              ribbon:
                enabled: true
                mode: POD
                cluster-domain: cluster.local
              discovery:
                all-namespaces: true
                enabled: true 
              config:
                enabled: true
                name: ${spring.application.name}
                namespace: default
              reload:
                enabled: true
                monitoring-config-maps: true
                monitoring-secrets: true
                strategy: refresh
                mode: event
                period: 15s
              
          profiles:
            active: dev
          sleuth:
            sampler:
              probability: 1.0
            traceId128: true
            enabled: true  
          zipkin:
            enabled: true
        last:
          applied:
            profile: application_default    
        logging: 
            level:
              root: trace
        ribbon:
            http:
            client:
              enabled: true 
            
        #'dev' profile only 
        --- 
        spring:
          profiles: dev 
        last:
          applied:
            profile: application_dev
          
        
        #'prod' profile only 
        --- 
        spring:
          profiles: prod 
        last:
          applied:
            profile: application_prod  