apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: simple-production
spec:
  strategy: production
  storage:
    type: elasticsearch
    options:
      es:
        server-urls: http://elasticsearch:9200