apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: service-discovery-client-role
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["services", "pods", "configmaps", "endpoints"]
  verbs: ["get", "watch", "list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: service-discovery-client-role-binding
  namespace: default
roleRef:
  kind: Role
  name: service-discovery-client-role
  apiGroup: ""
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
    apiGroup: ""