apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-micro-business-remoting
  labels:
    app: business-remoting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: business-remoting-app
  template:
    metadata:
      labels:
        app: business-remoting-app
    spec:
      containers:
      - name: spring-micro-business-remoting
        image: pintu12345/spring-micro-business-remoting:v2
        ports:
        - containerPort: 8000
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: dev