apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: my-cluster
spec:
  kafka:
    version: 2.3.0
    replicas: 3
    listeners:
#i added for node port access      
      external:
        type: nodeport
        tls: false
        overrides:
          bootstrap:
            nodePort: 32100
            address: 34.68.133.9
          brokers:
          - broker: 0
            advertisedHost: 34.68.133.9
           # advertisedPort: 12340
            nodePort: 32000
          - broker: 1
            advertisedHost: 34.68.133.9
           # advertisedPort: 12341
            nodePort: 32001
          - broker: 2
            advertisedHost: 34.68.133.9
           # advertisedPort: 12342
            nodePort: 32002
# ends here      
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      log.message.format.version: "2.3"
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 30Gi
        deleteClaim: false
  zookeeper:
    replicas: 3
    storage:
      type: persistent-claim
      size: 30Gi
      deleteClaim: false
  entityOperator:
    topicOperator: {}
    userOperator: {}

